name: Update All Calendars

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: zijie1024
          outputs: |
            dist/calendar-last-year-snake.svg
            dist/calendar-last-year-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate 3D Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: dist/calendar-last-year-3d.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_title: ""
          output_action: none

      - name: Generate 5-Year Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: dist/calendar-last-5year.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 5
          plugin_calendar_title: ""
          output_action: none

      - name: Modify SVGs
        run: |
          # 直接操作 dist 下的文件。如果文件不存在，sed 会报错并让 Action 失败，暴露问题
          sed -i '/<h2 class="field">/,/<\/h2>/d' dist/calendar-last-year-3d.svg
          sed -i 's/#58a6ff/#8b949e/g' dist/calendar-last-year-3d.svg
          
          sed -i '/<h2 class="field">/,/<\/h2>/d' dist/calendar-last-5year.svg

      - name: Commit all files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update metrics and calendars"
          file_pattern: dist/*
