name: UpdateCalendars

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: zijie1024
          outputs: |
            dist/calendar-last-year-snake.svg
            dist/calendar-last-year-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate 3D Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendar-last-year-3d.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: none

      - name: Generate 5-Year Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: calendar-last-5year.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 5
          output_action: none

      - name: Move and Modify SVGs
        run: |
          mv calendar-last-year-3d.svg dist/
          mv calendar-last-5year.svg dist/
          sed -i '/<h2 class="field">/,/<\/h2>/d' dist/calendar-last-year-3d.svg
          sed -i '/<h2 class="field">/,/<\/h2>/d' dist/calendar-last-5year.svg
          sed -i 's/#58a6ff/#8b949e/g' dist/calendar-last-year-3d.svg

      - name: Commit all files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist/*
